# Generated by Django 3.2.5 on 2021-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activeoffers', models.IntegerField()),
                ('allovers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('plant', models.ManyToManyField(to='Pflanzenverwaltung.Plant')),
                ('provider', models.ManyToManyField(to='Pflanzenverwaltung.User')),
            ],
        ),
    ]
